# Generated by Django 5.0.4 on 2024-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default="2000-12-02 10:02"),
            preserve_default=False,
        ),
    ]
