# Generated by Django 5.0.4 on 2024-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0002_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='timestamp',
        ),
    ]
