# Generated by Django 5.0.4 on 2024-04-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0004_post_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
