# Generated by Django 5.0.4 on 2024-04-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_postdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='all_comments', to='app_postdetails.comment'),
        ),
    ]
